steps:
  - name: "gcr.io/kaniko-project/executor:v1.6.0"
    args:
      - --destination=us.gcr.io/$PROJECT_ID/formidable
      - --cache=true
      - --cache-ttl=500h
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - formidable
      - --platform=managed
      - --image=us.gcr.io/$PROJECT_ID/formidable:latest
      - --region=us-central1
      - --quiet
# images: ["gcr.io/$PROJECT_ID/formidable"]
