steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/formidable", "."]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - formidable
      - --platform=managed
      - --image=us.gcr.io/$PROJECT_ID/formidable:latest
      - --region=us-central1
      - --quiet
    images: ["gcr.io/$PROJECT_ID/formidable"]
